#pragma once

#include "LineOfSightComponent.h"
#include "Perception/ParadoxTemporalVisionTypes.h"
#include "ParadoxTemporalVisionComponent.generated.h"

class UPrimitiveComponent;

/** Actor-level overlap state used to deduplicate multiple target components. */
struct FParadoxTemporalActorOverlapState
{
	TSet<TWeakObjectPtr<UPrimitiveComponent>> Components;
	bool bBroadcastForCurrentAuthority = false;
};

/**
 * Clone-owned authoritative perception geometry.
 *
 * The plugin's traces shape the visible mesh. Only physical overlaps generated by that same
 * procedural mesh are forwarded as temporal candidates.
 */
UCLASS(ClassGroup = (Paradox), BlueprintType, Blueprintable, meta = (BlueprintSpawnableComponent))
class PARADOX_API UParadoxTemporalVisionComponent : public ULineOfSightComponent
{
	GENERATED_BODY()

public:
	UParadoxTemporalVisionComponent(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());

	UPROPERTY(BlueprintAssignable, Category = "Paradox|Temporal Vision|Events")
	FParadoxTemporalOverlapEvent OnTemporalOverlapDetected;

	/** Builds an up-to-date collision mesh while keeping temporal authority disabled. */
	UFUNCTION(BlueprintCallable, Category = "Paradox|Temporal Vision")
	bool PrepareTemporalVision(FString& OutFailure);

	/** Releases actor-level candidate delivery for one synchronized run. */
	UFUNCTION(BlueprintCallable, Category = "Paradox|Temporal Vision")
	void EnableTemporalDetection(int32 InDetectionSessionId);

	/** Revokes authority before rewind, reset, presentation or teardown. */
	UFUNCTION(BlueprintCallable, Category = "Paradox|Temporal Vision")
	void DisableTemporalDetection(bool bClearPhysicalOverlapState = true);

	UFUNCTION(BlueprintPure, Category = "Paradox|Temporal Vision")
	bool IsTemporalDetectionAuthoritative() const { return bDetectionAuthoritative; }

	UFUNCTION(BlueprintPure, Category = "Paradox|Temporal Vision")
	int32 GetDetectionSessionId() const { return DetectionSessionId; }

	UFUNCTION(BlueprintPure, Category = "Paradox|Temporal Vision")
	int32 GetDeduplicatedOverlapActorCount() const { return ActorOverlapStates.Num(); }

	UFUNCTION(BlueprintPure, Category = "Paradox|Temporal Vision")
	FParadoxTemporalOverlapSnapshot GetLastPhysicalOverlap() const { return LastPhysicalOverlap; }

	UFUNCTION(BlueprintPure, Category = "Paradox|Temporal Vision|Debug")
	FParadoxTemporalVisionDebugSnapshot GetDebugSnapshot() const;

protected:
	virtual void TickComponent(
		float DeltaTime,
		ELevelTick TickType,
		FActorComponentTickFunction* ThisTickFunction) override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

	/** Object channel used by temporal target primitives. Defaults to Pawn. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Paradox|Temporal Vision|Collision")
	TEnumAsByte<ECollisionChannel> TemporalTargetObjectChannel = ECC_Pawn;

	/** Channel used only to shape the LineOfSight mesh around level occluders. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Paradox|Temporal Vision|Mesh")
	TEnumAsByte<ECollisionChannel> MeshOcclusionTraceChannel = ECC_Visibility;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Paradox|Temporal Vision|Mesh", meta = (ClampMin = "1", UIMin = "1"))
	int32 TraceResolution = 60;

	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Paradox|Temporal Vision|Debug")
	bool bEnableDebug = false;

private:
	UFUNCTION()
	void HandlePhysicalBeginOverlap(
		UPrimitiveComponent* OverlappedComponent,
		AActor* OtherActor,
		UPrimitiveComponent* OtherComponent,
		int32 OtherBodyIndex,
		bool bFromSweep,
		const FHitResult& SweepResult);

	UFUNCTION()
	void HandlePhysicalEndOverlap(
		UPrimitiveComponent* OverlappedComponent,
		AActor* OtherActor,
		UPrimitiveComponent* OtherComponent,
		int32 OtherBodyIndex);

	void ReconcileExistingOverlaps();
	void TrackPhysicalOverlap(AActor* OtherActor, UPrimitiveComponent* OtherComponent);
	void BroadcastActorCandidate(
		AActor& OtherActor,
		UPrimitiveComponent* RepresentativeComponent,
		FParadoxTemporalActorOverlapState& State);
	FParadoxTemporalOverlapSnapshot MakeSnapshot(
		AActor& OtherActor,
		UPrimitiveComponent* RepresentativeComponent,
		int32 ComponentCount) const;
	void DrawTemporalDebug() const;

	TMap<TWeakObjectPtr<AActor>, FParadoxTemporalActorOverlapState> ActorOverlapStates;

	UPROPERTY(Transient)
	FParadoxTemporalOverlapSnapshot LastPhysicalOverlap;

	int32 DetectionSessionId = INDEX_NONE;
	bool bDetectionAuthoritative = false;
	bool bPhysicalDelegatesBound = false;
};
